---
- include: scenarios/quick_auto.yml
  when: 
    - vol_size == 0
    - floating_ip is not defined
  static: False

- include: scenarios/quick.yml
  when: 
    - vol_size == 0
    - floating_ip is defined
  static: False

- include: scenarios/vol_auto.yml
  when:
    - vol_size != 0
    - floating_ip is not defined
  static: False

- include: scenarios/vol.yml
  when:
    - vol_size != 0
    - floating_ip is defined
  static: False