---
- include: templates/quick_auto.yml
  when: 
    - vol_size == 0
    - floating_ip is not defined
  static: False

- include: templates/quick.yml
  when: 
    - vol_size == 0
    - floating_ip is defined
  static: False

- include: templates/vol_auto.yml
  when:
    - vol_size != 0
    - floating_ip is not defined
  static: False

- include: templates/vol.yml
  when:
    - vol_size != 0
    - floating_ip is defined
  static: False